pierwsze=[5,10,15,20,25,30]
pierwsze.append(35)
print(len(pierwsze))
print(pierwsze[1:4])
print(pierwsze[:-1])
print(reversed(pierwsze))
#remove
print(max(pierwsze))
print(sum(pierwsze))
#count